databases:
  - name: odontogest-db
    databaseName: odontogest
    plan: basic-256mb

services:
  - type: web
    name: odontogest-web
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    preDeployCommand: "python manage.py migrate_schemas --shared && python manage.py migrate_schemas && python manage.py bootstrap_public_tenant && python manage.py bootstrap_superadmin && python manage.py seed_demo"
    startCommand: "gunicorn odontogest.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: MARCA_APP_NOMBRE
        value: "OdontoGest"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "jriquezes87@gmail.com"
      - key: ADMIN_PASSWORD
        generateValue: true
