# Generated by Django 5.0.14 on 2026-07-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="consultorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="core.consultorio",
            ),
        ),
    ]
