# Generated by Django 5.0.14 on 2026-07-22 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistio')], default='pendiente', max_length=20)),
                ('recordatorio_whatsapp_horas_antes', models.PositiveIntegerField(default=24, help_text='Cuantas horas antes de la cita se envia el recordatorio')),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cita_generada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_numero', models.CharField(blank=True, max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('detalles', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pacientes/fotos/%Y/%m/')),
                ('momento', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('despues', 'Despues')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento_realizado', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Historias clinicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_numero', models.CharField(max_length=10)),
                ('hallazgo', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado / Resina'), ('corona', 'Corona'), ('endodoncia', 'Endodoncia'), ('extraccion', 'Extraccion indicada'), ('ausente', 'Ausente'), ('implante', 'Implante'), ('sellante', 'Sellante'), ('fractura', 'Fractura')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Registro de odontograma',
                'verbose_name_plural': 'Registros de odontograma',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes_medicos', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PagoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
