# Generated by Django 5.0.14 on 2026-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="odontogramaregistro",
            name="agregado_a_cotizacion",
            field=models.BooleanField(default=False),
        ),
    ]
