# Generated by Django 5.0.14 on 2026-07-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_odontogramaregistro_agregado_a_cotizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagopaciente",
            name="cotizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="clientes.cotizacion",
            ),
        ),
    ]
