# Generated by Django 5.0.14 on 2026-07-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_pagopaciente_cotizacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cotizacionitem",
            options={"ordering": ["orden", "id"]},
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="completado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="orden",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
